name: Sync Documentation from BetterGov

on:
  schedule:
    # Run every 12 hours to check for updates
    - cron: '0 */12 * * *'
  workflow_dispatch:
    # Allow manual triggering
  repository_dispatch:
    types: [sync-docs]

jobs:
  sync-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # temporarily disable cache to avoid stale node_modules issues
          cache: 'none'

      - name: Check Node.js and npm versions
        run: |
          node -v
          npm -v

      - name: Clean existing modules
        run: |
          rm -rf node_modules
          rm -f package-lock.json

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci || npm install

      - name: List installed picomatch versions
        run: npm ls picomatch || true

      - name: Sync documentation from BetterGov
        run: |
          node scripts/sync-docs.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "docs: sync documentation from BetterGov repository [skip ci]"
          git push
