name: Sync Documentation from BetterGov

on:
  schedule:
    # Run every 12 hours to check for updates
    - cron: '0 */12 * * *'
  workflow_dispatch:
    # Allow manual triggering
  repository_dispatch:
    types: [sync-docs]

jobs:
  sync-docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Sync documentation from BetterGov
        run: |
          node scripts/sync-docs.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "docs: sync documentation from BetterGov repository [skip ci]"
          git push

      - name: Create Pull Request if needed
        if: steps.verify-changed-files.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "docs: sync documentation from BetterGov repository"
          title: "Sync Documentation from BetterGov"
          body: |
            This PR automatically syncs documentation files from the main BetterGov repository.
            
            **Files synced:**
            - Documentation files from `docs/` directory
            - README.md updates
            - Other markdown files as configured
            
            **Source:** [bettergovph/bettergov](https://github.com/bettergovph/bettergov)
          branch: sync-docs-from-bettergov
          delete-branch: true
